# Generated by Django 3.2.11 on 2022-04-22 14:54

from django.db import migrations, models

import findthatcharity.apps.ftc.models.orgid


class Migration(migrations.Migration):
    dependencies = [
        ("other_data", "0012_genderpaygap_companywebsite"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiDataItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_id",
                    findthatcharity.apps.ftc.models.orgid.OrgidField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        null=True,
                        verbose_name="Organisation Identifier",
                    ),
                ),
                ("wikidata_id", models.CharField(db_index=True, max_length=255)),
                (
                    "wikipedia_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("twitter", models.CharField(blank=True, max_length=255, null=True)),
                ("facebook", models.CharField(blank=True, max_length=255, null=True)),
                ("grid_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
