# Generated by Django 4.1.7 on 2023-05-16 15:16

from django.db import migrations, models

import findthatcharity.apps.ftc.models.orgid


class Migration(migrations.Migration):
    dependencies = [
        ("other_data", "0017_grant_recipientindividual_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="fundingOrganization_canonical_id",
            field=findthatcharity.apps.ftc.models.orgid.OrgidField(
                blank=True,
                db_index=True,
                help_text="DEPRECATED - do not use this field",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="fundingOrganization_canonical_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="DEPRECATED - do not use this field",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="recipientOrganization_canonical_id",
            field=findthatcharity.apps.ftc.models.orgid.OrgidField(
                blank=True,
                db_index=True,
                help_text="DEPRECATED - do not use this field",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="recipientOrganization_canonical_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="DEPRECATED - do not use this field",
                max_length=255,
                null=True,
            ),
        ),
    ]
