# Generated by Django 3.0.6 on 2020-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0005_auto_20200705_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccewcharity",
            name="add1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="add2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="add3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="add4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="add5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="aob",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="aob_defined",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="corr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="fax",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="gd",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="ha_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="nhs",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="orgtype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharity",
            name="postcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharityaoo",
            name="master",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewcharityaoo",
            name="welsh",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewfinancial",
            name="expend",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewfinancial",
            name="income",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="coyno",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="fyend",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="grouptype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="income",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="incomedate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="trustees",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="web",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewmaincharity",
            name="welsh",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="asset_close",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="asset_gain",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="asset_open",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="cash_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="charity_acc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="cons_acc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="credit_1",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="credit_long",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="current_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="employees",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_charble",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_dep",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_gov",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_grant",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_invest",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_other",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_support",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_total",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_trade",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="exp_vol",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="fixed_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="funds_end",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="funds_restrict",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="funds_total",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="funds_unrestrict",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="inc_char",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="inc_end",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="inc_fr",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="inc_invest",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="inc_leg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="inc_other",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="inc_total",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="inc_vol",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="invest_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="invest_gain",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="open_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="pension_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="pension_gain",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="reserves",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="total_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewpartb",
            name="volunteers",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ccewregistration",
            name="remcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ccewregistration",
            name="remdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
