# Generated by Django 3.1 on 2020-08-04 09:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0007_auto_20200731_1726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityraw",
            name="data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
