# Generated by Django 3.1 on 2020-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0008_auto_20200804_1019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityfinancial",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("consolidated", "Consolidated"),
                    ("charity", "Charity"),
                    ("basic_oscr", "Basic (OSCR)"),
                    ("detailed_oscr", "Detailed (OSCR)"),
                    ("basic_ccni", "Basic (CCNI)"),
                    ("detailed_ccni", "Detailed (CCNI)"),
                ],
                default="basic",
                max_length=50,
            ),
        ),
    ]
