# Generated by Django 3.1.1 on 2021-04-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charity", "0009_auto_20200921_1156"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CCEWCharity",
        ),
        migrations.DeleteModel(
            name="CCEWCharityAOO",
        ),
        migrations.DeleteModel(
            name="CCEWClass",
        ),
        migrations.DeleteModel(
            name="CCEWFinancial",
        ),
        migrations.DeleteModel(
            name="CCEWMainCharity",
        ),
        migrations.DeleteModel(
            name="CCEWName",
        ),
        migrations.DeleteModel(
            name="CCEWObjects",
        ),
        migrations.DeleteModel(
            name="CCEWPartB",
        ),
        migrations.DeleteModel(
            name="CCEWRegistration",
        ),
    ]
