# Generated by Django 3.1.1 on 2021-04-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_ccew_updated_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccewcharityeventhistory',
            name='charity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
