# Generated by Django 3.2.5 on 2021-08-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charity",
            "0012_alter_ccewcharityareaofoperation_geographic_area_description",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="areaofoperation",
            name="aooname",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="areaofoperation",
            name="aoosort",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="charity",
            name="company_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="charity",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="charity",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="charity",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="charity",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="charity",
            name="postcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="charity",
            name="removal_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="charity",
            name="source",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="charityname",
            name="name_type",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="charityraw",
            name="org_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="charityraw",
            name="spider",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="title",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
