# Generated by Django 3.1.1 on 2021-04-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity", "0013_auto_20210404_2125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityname",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
