# Generated by Django 3.2.5 on 2021-10-07 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0014_auto_20210902_1630"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ccewcharitypublishedreport",
            old_name="charity_id",
            new_name="organisation_number",
        ),
    ]
