# Generated by Django 3.1.1 on 2021-04-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0015_auto_20210404_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CcewDataFile',
        ),
    ]
