# Generated by Django 3.2.11 on 2022-02-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0017_auto_20220118_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='classification',
        ),
    ]
