# Generated by Django 5.2 on 2025-08-21 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0021_charityaddresshistory"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE charity_ccewcharitytrustee
            SET trustee_name = ''
            WHERE individual_or_organisation != 'O'
            """
        )
    ]
