# Generated by Django 6.0.2 on 2026-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0022_auto_20250821_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="charityfinancial",
            name="inc_govt_contracts",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charityfinancial",
            name="inc_govt_grants",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
