# Generated by Django 6.0.4 on 2026-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0023_charityfinancial_inc_govt_contracts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="web",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
