# Generated by Django 3.1 on 2020-08-06 13:59

import django_better_admin_arrayfield.models.fields
from django.db import migrations

import ftc.models


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0005_auto_20200804_1019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="orgIDs",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=ftc.models.OrgidField(blank=True, max_length=200),
                size=None,
                verbose_name="Other organisation identifiers",
            ),
        ),
    ]
