# Generated by Django 3.1.1 on 2021-02-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0011_organisationlocation_scrape"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="location",
        ),
    ]
