# Generated by Django 3.1.1 on 2021-02-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0012_remove_organisation_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="geo_ctry",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_cty",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_lat",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_laua",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_lep1",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_lep2",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_long",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_lsoa11",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_msoa11",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_oa11",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_pcon",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_rgn",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_ttwa",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="geo_ward",
        ),
    ]
