# Generated by Django 3.2 on 2021-04-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0014_auto_20210417_1040"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationlocation",
            name="spider",
            field=models.CharField(db_index=True, default="spider", max_length=200),
            preserve_default=False,
        ),
    ]
