# Generated by Django 3.2 on 2021-04-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0016_remove_organisationlocation_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="org_id_scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ftc.orgidscheme",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="organisationTypePrimary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organisations",
                to="ftc.organisationtype",
                verbose_name="Primary organisation type",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="scrape",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organisations",
                to="ftc.scrape",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organisations",
                to="ftc.source",
            ),
        ),
        migrations.AlterField(
            model_name="organisationlink",
            name="scrape",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organisation_links",
                to="ftc.scrape",
            ),
        ),
        migrations.AlterField(
            model_name="organisationlink",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organisation_links",
                to="ftc.source",
            ),
        ),
        migrations.AlterField(
            model_name="organisationlocation",
            name="scrape",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organisation_locations",
                to="ftc.scrape",
            ),
        ),
        migrations.AlterField(
            model_name="organisationlocation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organisation_locations",
                to="ftc.source",
            ),
        ),
    ]
