# Generated by Django 3.2.5 on 2021-10-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0017_auto_20210419_1620'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationlocation',
            unique_together={('org_id', 'name', 'geoCodeType', 'locationType', 'spider', 'source_id', 'scrape_id')},
        ),
    ]
