# Generated by Django 3.2.11 on 2022-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0020_organisationclassification"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="slug",
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="single",
            field=models.BooleanField(default=True),
        ),
    ]
