# Generated by Django 3.2.11 on 2022-01-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0021_auto_20220120_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="single",
            field=models.BooleanField(default=False),
        ),
    ]
