# Generated by Django 3.2.11 on 2022-01-20 16:20

from django.db import migrations

ALL_VOCABULARIES = {
    "ccni_purposes": {
        "slug": "ccni_purposes",
        "title": "Purposes (CCNI)",
        "description": "",
        "single": False,
    },
    "ccni_theme": {
        "slug": "ccni_theme",
        "title": "Theme (CCNI)",
        "description": "",
        "single": False,
    },
    "ccni_beneficiaries": {
        "slug": "ccni_beneficiaries",
        "title": "Beneficiaries (CCNI)",
        "description": "",
        "single": False,
    },
    "oscr_activities": {
        "slug": "oscr_activities",
        "title": "Activities (OSCR)",
        "description": "",
        "single": False,
    },
    "oscr_beneficiaries": {
        "slug": "oscr_beneficiaries",
        "title": "Beneficiaries (OSCR)",
        "description": "",
        "single": False,
    },
    "oscr_purposes": {
        "slug": "oscr_purposes",
        "title": "Purposes (OSCR)",
        "description": "",
        "single": False,
    },
    "International Classification of Non-profit and Third Sector Organizations (ICNP/TSO)": {
        "slug": "icnptso",
        "title": "International Classification of Non-profit and Third Sector Organizations (ICNP/TSO)",
        "description": "",
        "single": False,
    },
    "UK Charity Activity Tags": {
        "slug": "ukcat",
        "title": "UK Charity Activity Tags",
        "description": "",
        "single": False,
    },
    "Companies House SIC Codes": {
        "slug": "ch_sic",
        "title": "Companies House SIC Codes",
        "description": "",
        "single": False,
    },
    "ccew_theme": {
        "slug": "ccew_theme",
        "title": "Theme (CCEW)",
        "description": "",
        "single": False,
    },
    "ccew_beneficiaries": {
        "slug": "ccew_beneficiaries",
        "title": "Beneficiaries (CCEW)",
        "description": "",
        "single": False,
    },
    "ccew_activities": {
        "slug": "ccew_activities",
        "title": "Activities (CCEW)",
        "description": "",
        "single": False,
    },
    "International Classification of Non Profit Organisations (ICNPO)": {
        "slug": "icnpo",
        "title": "International Classification of Non Profit Organisations (ICNPO)",
        "description": "",
        "single": False,
    },
}


def update_vocabularies(apps, schema_editor):
    Vocabulary = apps.get_model("ftc", "Vocabulary")
    for existing_title, new_data in ALL_VOCABULARIES.items():
        existing_vocabulary = Vocabulary.objects.filter(title=existing_title).first()
        if existing_vocabulary:
            existing_vocabulary.slug = new_data["slug"]
            existing_vocabulary.title = new_data["title"]
            existing_vocabulary.description = new_data["description"]
            existing_vocabulary.single = new_data["single"]
            existing_vocabulary.save()
        else:
            Vocabulary.objects.create(**new_data)


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0022_auto_20220120_1618"),
    ]

    operations = [
        migrations.RunPython(update_vocabularies),
    ]
