# Generated by Django 3.2.11 on 2022-01-20 16:38

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0023_auto_20220120_1620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
