# Generated by Django 3.2.13 on 2022-07-01 10:49

from django.db import migrations


def delete_grid_records(apps, schema_editor):
    Organisation = apps.get_model("ftc", "Organisation")
    Organisation.objects.filter(spider="grid").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0025_alter_organisation_linked_orgs"),
    ]

    operations = [
        migrations.RunPython(delete_grid_records),
    ]
