# Generated by Django 4.1.1 on 2022-09-07 19:31

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0026_auto_20220701_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="priority",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.BigIntegerField(blank=True, db_index=True, null=True),
                blank=True,
                null=True,
                size=None,
                verbose_name="Organisation priority",
            ),
        ),
    ]
