# Generated by Django 3.2.13 on 2022-07-18 12:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0026_auto_20220701_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="ftc_organis_search__ac2863_gin"
            ),
        ),
    ]
