# Generated by Django 4.1 on 2022-08-12 13:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import ftc.models.orgid


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0027_auto_20220718_1330"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_id",
                    ftc.models.orgid.OrgidField(
                        db_index=True,
                        max_length=200,
                        verbose_name="Organisation Identifier",
                    ),
                ),
                (
                    "orgIDs",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=ftc.models.orgid.OrgidField(
                            blank=True, max_length=200
                        ),
                        size=None,
                        verbose_name="Other organisation identifiers",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "sortname",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Sort Name"
                    ),
                ),
                (
                    "alternateName",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Other names",
                    ),
                ),
                (
                    "postalCode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Postcode",
                    ),
                ),
                (
                    "domain",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Website domain",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(blank=True, null=True, verbose_name="Active"),
                ),
                (
                    "organisationType",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Other organisation types",
                    ),
                ),
                (
                    "source",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Data source",
                    ),
                ),
                (
                    "locations",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Locations",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("search_scale", models.FloatField(db_index=True, default=1)),
                (
                    "spider",
                    models.CharField(
                        db_index=True, default="update_index", max_length=200
                    ),
                ),
                (
                    "organisationTypePrimary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organisation_groups",
                        to="ftc.organisationtype",
                        verbose_name="Primary organisation type",
                    ),
                ),
                (
                    "scrape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organisation_groups",
                        to="ftc.scrape",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="organisationgroup",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["orgIDs"], name="ftc_organis_orgIDs_083ddf_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationgroup",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["alternateName"], name="ftc_organis_alterna_d1c645_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationgroup",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["organisationType"], name="ftc_organis_organis_60ab08_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationgroup",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["locations"], name="ftc_organis_locatio_138ed6_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationgroup",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="ftc_organis_search__dbbed8_gin"
            ),
        ),
    ]
