# Generated by Django 5.0.4 on 2024-06-28 11:05

import os

from django.db import migrations, models

current_dir = os.path.dirname(__file__)
with open(os.path.join(current_dir, "../models/charity_data_query.sql"), "r") as f:
    view_sql = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0029_organisationlocation_geo_lsoa21_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharityData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("ccew", "Charity Commission for England and Wales")],
                        default="ccew",
                        max_length=255,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("data", models.JSONField()),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.RunSQL(
            sql=[
                f"""
                CREATE MATERIALIZED VIEW "ftc_charitydata" AS (
                    {view_sql}
                )
                """,
                "CREATE INDEX ftc_charitydata_id_idx ON ftc_charitydata (id)",
                "CREATE INDEX ftc_charitydata_active_idx ON ftc_charitydata (active)",
                "CREATE INDEX ftc_charitydata_source_idx ON ftc_charitydata (source)",
            ],
            reverse_sql='DROP MATERIALIZED VIEW "ftc_charitydata"',
            hints={"modelname": "charitydata"},
        ),
    ]
