# Generated by Django 4.1 on 2022-09-07 10:15

from django.db import migrations, models
import ftc.models.orgid


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0029_organisation_priority"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="organisationgroup",
            name="ftc_organis_organis_60ab08_gin",
        ),
        migrations.RemoveField(
            model_name="organisationgroup",
            name="id",
        ),
        migrations.RemoveField(
            model_name="organisationgroup",
            name="scrape",
        ),
        migrations.RemoveField(
            model_name="organisationgroup",
            name="spider",
        ),
        migrations.AlterField(
            model_name="organisationgroup",
            name="org_id",
            field=ftc.models.orgid.OrgidField(
                db_index=True,
                max_length=200,
                primary_key=True,
                serialize=False,
                verbose_name="Organisation Identifier",
            ),
        ),
        migrations.RemoveField(
            model_name="organisationgroup",
            name="organisationType",
        ),
        migrations.AddField(
            model_name="organisationgroup",
            name="organisationType",
            field=models.ManyToManyField(
                to="ftc.organisationtype", verbose_name="Other organisation types"
            ),
        ),
    ]
