# Generated by Django 5.0.4 on 2024-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0030_charitydata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="parent",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=200,
                null=True,
                verbose_name="Parent organisation",
            ),
        ),
    ]
