# Generated by Django 5.0.4 on 2024-07-17 15:38

import django.contrib.postgres.indexes
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0032_organisation_linked_orgs_official_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="organisation",
            name="ftc_organis_linked__bff241_gin",
        ),
        migrations.RenameField(
            model_name="organisation",
            old_name="linked_orgs_official",
            new_name="linked_orgs_verified",
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["linked_orgs_verified"], name="ftc_organis_linked__00053d_gin"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="linked_orgs_verified",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200),
                blank=True,
                null=True,
                size=None,
                verbose_name="Linked organisations (verified sources)",
            ),
        ),
    ]
