# Generated by Django 5.0.4 on 2025-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0039_auto_20250224_1439"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "org_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Organisation Identifier",
                    ),
                ),
            ],
        ),
    ]
