# Generated by Django 6.0.4 on 2026-07-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0047_alter_organisation_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldata",
            name="remove_organisation_name",
            field=models.BooleanField(
                default=False,
                help_text="Remove the organisation name from the database",
            ),
        ),
    ]
