# Generated by Django 3.2.5 on 2021-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0013_auto_20210818_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="charity",
            name="employees",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="charity",
            name="trustees",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charity",
            name="volunteers",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
