# Generated by Django 3.2.5 on 2022-01-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other_data", "0011_alter_cqclocation_classification"),
        ("ftc", "0019_vocabulary_vocabularyentries"),
        ("charity", "0016_auto_20211007_1057"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vocabularyentries",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="vocabularyentries",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="vocabularyentries",
            name="vocabulary",
        ),
        migrations.AlterField(
            model_name="charity",
            name="classification",
            field=models.ManyToManyField(to="ftc.VocabularyEntries"),
        ),
        migrations.DeleteModel(
            name="Vocabulary",
        ),
        migrations.DeleteModel(
            name="VocabularyEntries",
        ),
    ]
