# Generated by Django 3.2 on 2021-04-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ftc", "0017_auto_20210419_1620"),
        ("other_data", "0007_cqcbrand_cqclocation_cqcprovider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genderpaygap",
            name="scrape",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="ftc.scrape"
            ),
        ),
    ]
