# Generated by Django 3.2.5 on 2022-01-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0019_vocabulary_vocabularyentries"),
        ("other_data", "0010_grant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cqclocation",
            name="classification",
            field=models.ManyToManyField(to="ftc.VocabularyEntries"),
        ),
    ]
