# Generated by Django 3.2.11 on 2022-03-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other_data", "0011_alter_cqclocation_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="genderpaygap",
            name="CompanyWebsite",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
