# Generated by Django 3.2.11 on 2022-04-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0025_alter_organisation_linked_orgs"),
        ("other_data", "0013_wikidataitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikidataitem",
            name="scrape",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ftc.scrape",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wikidataitem",
            name="spider",
            field=models.CharField(db_index=True, default="wd", max_length=200),
        ),
    ]
