# Generated by Django 4.1.4 on 2022-12-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("other_data", "0014_auto_20220422_1603"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cqclocation",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="cqcprovider",
            name="brand",
        ),
    ]
