# Generated by Django 4.1.4 on 2023-01-10 15:31

from django.db import migrations, models

import ftc.models.orgid


def forwards_func(apps, schema_editor):
    Grant = apps.get_model("other_data", "Grant")
    Grant.objects.update(
        fundingOrganization_canonical_id=models.F("fundingOrganization_id"),
        fundingOrganization_canonical_name=models.F("fundingOrganization_name"),
        recipientOrganization_canonical_id=models.F("recipientOrganization_id"),
        recipientOrganization_canonical_name=models.F("recipientOrganization_name"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("other_data", "0015_remove_cqclocation_provider_remove_cqcprovider_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="fundingOrganization_canonical_id",
            field=ftc.models.orgid.OrgidField(
                db_index=True, default="id", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grant",
            name="fundingOrganization_canonical_name",
            field=models.CharField(db_index=True, default="name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grant",
            name="fundingOrganization_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="grantProgramme_title",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="plannedDates_duration",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="plannedDates_endDate",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="plannedDates_startDate",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="recipientOrganization_canonical_id",
            field=ftc.models.orgid.OrgidField(
                db_index=True, default="id", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grant",
            name="recipientOrganization_canonical_name",
            field=models.CharField(db_index=True, default="name", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
