# Generated by Django 5.2 on 2025-10-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("other_data", "0018_alter_grant_fundingorganization_canonical_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikidataitem",
            name="bluesky",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wikidataitem",
            name="instagram",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wikidataitem",
            name="linkedin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wikidataitem",
            name="youtube",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
