# Generated by Django 6.0.4 on 2026-05-01 08:52

import django.db.models.deletion
from django.db import migrations, models

import ftc.models.orgid


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0046_auto_20260117_1711"),
        ("other_data", "0019_wikidataitem_bluesky_wikidataitem_instagram_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIC",
            fields=[
                (
                    "uid",
                    ftc.models.orgid.OrgidField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Organisation Identifier",
                    ),
                ),
                (
                    "company_number",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Companies House registration number",
                    ),
                ),
                (
                    "regy",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Year of incorporation"
                    ),
                ),
                (
                    "remy",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Year of dissolution"
                    ),
                ),
                (
                    "beneficiaries",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section A: Who the companyʼs activities will benefit",
                    ),
                ),
                (
                    "surplus_use",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How any surplus will be used for community benefit",
                    ),
                ),
                (
                    "activity_1",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 1",
                    ),
                ),
                (
                    "community_benefit_1",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 1",
                    ),
                ),
                (
                    "activity_2",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 2",
                    ),
                ),
                (
                    "community_benefit_2",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 2",
                    ),
                ),
                (
                    "activity_3",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 3",
                    ),
                ),
                (
                    "community_benefit_3",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 3",
                    ),
                ),
                (
                    "activity_4",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 4",
                    ),
                ),
                (
                    "community_benefit_4",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 4",
                    ),
                ),
                (
                    "activity_5",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 5",
                    ),
                ),
                (
                    "community_benefit_5",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 5",
                    ),
                ),
                (
                    "activity_6",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 6",
                    ),
                ),
                (
                    "community_benefit_6",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 6",
                    ),
                ),
                (
                    "activity_7",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 7",
                    ),
                ),
                (
                    "community_benefit_7",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 7",
                    ),
                ),
                (
                    "activity_8",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 8",
                    ),
                ),
                (
                    "community_benefit_8",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 8",
                    ),
                ),
                (
                    "activity_9",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 9",
                    ),
                ),
                (
                    "community_benefit_9",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 9",
                    ),
                ),
                (
                    "activity_10",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: Description of activity 10",
                    ),
                ),
                (
                    "community_benefit_10",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Section B: How each activity benefits the community 10",
                    ),
                ),
                (
                    "spider",
                    models.CharField(
                        db_index=True, default="tscc-cic-36-forms", max_length=200
                    ),
                ),
                (
                    "scrape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="ftc.scrape"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cics",
                        to="ftc.source",
                    ),
                ),
            ],
        ),
    ]
