# Generated by Django 3.1.1 on 2020-10-01 16:08

from django.db import migrations, models

import findthatcharity.apps.ftc.models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_auto_20201001_1234"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationLocation",
            fields=[
                (
                    "organisation_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "org_id",
                    findthatcharity.apps.ftc.models.OrgidField(
                        db_index=True,
                        max_length=200,
                        verbose_name="Organisation Identifier",
                    ),
                ),
                ("pcds", models.CharField(db_index=True, max_length=8, unique=True)),
                ("oa11", models.CharField(blank=True, max_length=9, null=True)),
                ("cty", models.CharField(blank=True, max_length=9, null=True)),
                ("laua", models.CharField(blank=True, max_length=9, null=True)),
                ("ward", models.CharField(blank=True, max_length=9, null=True)),
                ("ctry", models.CharField(blank=True, max_length=9, null=True)),
                ("rgn", models.CharField(blank=True, max_length=9, null=True)),
                ("pcon", models.CharField(blank=True, max_length=9, null=True)),
                ("ttwa", models.CharField(blank=True, max_length=9, null=True)),
                ("lsoa11", models.CharField(blank=True, max_length=9, null=True)),
                ("msoa11", models.CharField(blank=True, max_length=9, null=True)),
                ("lep1", models.CharField(blank=True, max_length=9, null=True)),
                ("lep2", models.CharField(blank=True, max_length=9, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("long", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
