# Generated by Django 3.1.1 on 2020-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0003_organisationlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationlocation",
            name="pcds",
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
