# Generated by Django 3.1.1 on 2021-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0006_geolookup"),
    ]

    operations = [
        migrations.AddField(
            model_name="geolookup",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
