# Generated by Django 4.2.2 on 2023-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0008_alter_postcode_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="geolookup",
            name="geo_lsoa21",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=9,
                null=True,
                verbose_name="Lower Super Output Area (2021)",
            ),
        ),
        migrations.AddField(
            model_name="geolookup",
            name="geo_msoa21",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=9,
                null=True,
                verbose_name="Middle Super Output Area (2021)",
            ),
        ),
        migrations.AddField(
            model_name="geolookup",
            name="geo_oa21",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Output Area (2021)"
            ),
        ),
        migrations.AddField(
            model_name="postcode",
            name="lsoa21",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="postcode",
            name="msoa21",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="postcode",
            name="oa21",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="geolookup",
            name="geo_lsoa11",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=9,
                null=True,
                verbose_name="Lower Super Output Area (2011)",
            ),
        ),
        migrations.AlterField(
            model_name="geolookup",
            name="geo_msoa11",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=9,
                null=True,
                verbose_name="Middle Super Output Area (2011)",
            ),
        ),
        migrations.AlterField(
            model_name="geolookup",
            name="geo_oa11",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Output Area (2011)"
            ),
        ),
    ]
