# Generated by Django 3.2.11 on 2022-01-20 12:44

import django.db.models.deletion
from django.db import migrations, models

import ftc.models.orgid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ftc", "0020_organisationclassification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SICCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", ftc.models.orgid.OrgidField(db_index=True, max_length=200)),
                ("code", models.CharField(max_length=255)),
                (
                    "spider",
                    models.CharField(
                        db_index=True, default="companies", max_length=200
                    ),
                ),
                (
                    "scrape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="ftc.scrape"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreviousName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", ftc.models.orgid.OrgidField(db_index=True, max_length=200)),
                ("ConDate", models.DateField(blank=True, null=True)),
                ("CompanyName", models.CharField(max_length=255)),
                (
                    "spider",
                    models.CharField(
                        db_index=True, default="companies", max_length=200
                    ),
                ),
                (
                    "scrape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="ftc.scrape"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grant_id", models.CharField(db_index=True, max_length=255)),
                ("CompanyName", models.CharField(db_index=True, max_length=255)),
                ("CompanyNumber", models.CharField(db_index=True, max_length=10)),
                (
                    "RegAddress_CareOf",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_POBox",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_AddressLine1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_AddressLine2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_PostTown",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_County",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_Country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_PostCode",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "CompanyCategory",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "CompanyStatus",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "CountryOfOrigin",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "DissolutionDate",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "IncorporationDate",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("Accounts_AccountRefDay", models.IntegerField(blank=True, null=True)),
                (
                    "Accounts_AccountRefMonth",
                    models.IntegerField(blank=True, null=True),
                ),
                ("Accounts_NextDueDate", models.DateField(blank=True, null=True)),
                ("Accounts_LastMadeUpDate", models.DateField(blank=True, null=True)),
                (
                    "Accounts_AccountCategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Returns_NextDueDate", models.DateField(blank=True, null=True)),
                ("Returns_LastMadeUpDate", models.DateField(blank=True, null=True)),
                (
                    "Mortgages_NumMortCharges",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Mortgages_NumMortOutstanding",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Mortgages_NumMortPartSatisfied",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Mortgages_NumMortSatisfied",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "LimitedPartnerships_NumGenPartners",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "LimitedPartnerships_NumLimPartners",
                    models.IntegerField(blank=True, null=True),
                ),
                ("URI", models.URLField(blank=True, max_length=255, null=True)),
                ("ConfStmtNextDueDate", models.DateField(blank=True, null=True)),
                ("ConfStmtLastMadeUpDate", models.DateField(blank=True, null=True)),
                ("org_id", ftc.models.orgid.OrgidField(db_index=True, max_length=200)),
                (
                    "spider",
                    models.CharField(
                        db_index=True, default="companies", max_length=200
                    ),
                ),
                (
                    "scrape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="ftc.scrape"
                    ),
                ),
            ],
        ),
    ]
