# Generated by Django 3.2.11 on 2022-01-20 12:55

from django.db import migrations, models

import ftc.models.orgid


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", ftc.models.orgid.OrgidField(db_index=True, max_length=200)),
                ("financial_year_end", models.DateField(db_index=True)),
                ("category", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="company",
            name="grant_id",
        ),
    ]
