# Generated by Django 3.2.11 on 2022-01-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_account_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                choices=[
                    ("ACCOUNTS TYPE NOT AVAILABLE", "Accounts Type Not Available"),
                    ("AUDIT EXEMPTION SUBSIDIARY", "Audit Exemption Subsidiary"),
                    ("AUDITED ABRIDGED", "Audited Abridged"),
                    ("DORMANT", "Dormant"),
                    ("FILING EXEMPTION SUBSIDIARY", "Filing Exemption Subsidiary"),
                    ("FULL", "Full"),
                    ("GROUP", "Group"),
                    ("MEDIUM", "Medium"),
                    ("MICRO ENTITY", "Micro Entity"),
                    ("SMALL", "Small"),
                    ("TOTAL EXEMPTION FULL", "Total Exemption Full"),
                    ("TOTAL EXEMPTION SMALL", "Total Exemption Small"),
                    ("UNAUDITED ABRIDGED", "Unaudited Abridged"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Accounts_AccountCategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCOUNTS TYPE NOT AVAILABLE", "Accounts Type Not Available"),
                    ("AUDIT EXEMPTION SUBSIDIARY", "Audit Exemption Subsidiary"),
                    ("AUDITED ABRIDGED", "Audited Abridged"),
                    ("DORMANT", "Dormant"),
                    ("FILING EXEMPTION SUBSIDIARY", "Filing Exemption Subsidiary"),
                    ("FULL", "Full"),
                    ("GROUP", "Group"),
                    ("MEDIUM", "Medium"),
                    ("MICRO ENTITY", "Micro Entity"),
                    ("SMALL", "Small"),
                    ("TOTAL EXEMPTION FULL", "Total Exemption Full"),
                    ("TOTAL EXEMPTION SMALL", "Total Exemption Small"),
                    ("UNAUDITED ABRIDGED", "Unaudited Abridged"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="CompanyCategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Community Interest Company", "Cic"),
                    ("Charitable Incorporated Organisation", "Cio"),
                    (
                        "PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)",
                        "Clg",
                    ),
                    (
                        "PRI/LBG/NSC (Private, Limited by guarantee, no share capital, use of 'Limited' exemption)",
                        "Clg Limited",
                    ),
                    ("Converted/Closed", "Closed"),
                    ("European Public Limited-Liability Company (SE)", "Euro Plc"),
                    (
                        "Investment Company with Variable Capital",
                        "Investment Company With Variable Capital",
                    ),
                    (
                        "Investment Company with Variable Capital (Securities)",
                        "Investment Company With Variable Capital Securities",
                    ),
                    (
                        "Investment Company with Variable Capital(Umbrella)",
                        "Investment Company With Variable Capital Umbrella",
                    ),
                    ("Industrial and Provident Society", "Ips"),
                    ("Limited Partnership", "Limited Partnership"),
                    ("Limited Liability Partnership", "Llp"),
                    ("Old Public Company", "Old Public Company"),
                    ("Other company type", "Other Company Type"),
                    ("Public Limited Company", "Plc"),
                    ("Private Limited Company", "Private Limited Company"),
                    (
                        "PRIV LTD SECT. 30 (Private limited company, section 30 of the Companies Act)",
                        "Private Limited Company Sect30",
                    ),
                    ("Private Unlimited", "Private Unlimited"),
                    ("Private Unlimited Company", "Private Unlimited Company"),
                    ("Protected Cell Company", "Protected Cell Company"),
                    ("Royal Charter Company", "Rc"),
                    ("Registered Society", "Rs"),
                    ("Scottish Charitable Incorporated Organisation", "Scio"),
                    ("Scottish Partnership", "Scottish Partnership"),
                    (
                        "United Kingdom Economic Interest Grouping",
                        "United Kingdom Economic Interest Grouping",
                    ),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
    ]
