# Generated by Django 3.2.11 on 2022-01-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_auto_20220120_1316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                choices=[
                    ("ACCOUNTS TYPE NOT AVAILABLE", "Accounts Type Not Available"),
                    ("AUDIT EXEMPTION SUBSIDIARY", "Audit Exemption Subsidiary"),
                    ("AUDITED ABRIDGED", "Audited Abridged"),
                    ("DORMANT", "Dormant"),
                    ("FILING EXEMPTION SUBSIDIARY", "Filing Exemption Subsidiary"),
                    ("FULL", "Full"),
                    ("GROUP", "Group"),
                    ("MEDIUM", "Medium"),
                    ("MICRO ENTITY", "Micro Entity"),
                    ("SMALL", "Small"),
                    ("TOTAL EXEMPTION FULL", "Total Exemption Full"),
                    ("TOTAL EXEMPTION SMALL", "Total Exemption Small"),
                    ("UNAUDITED ABRIDGED", "Unaudited Abridged"),
                    ("NO ACCOUNTS FILED", "No Accounts Filed"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Accounts_AccountCategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCOUNTS TYPE NOT AVAILABLE", "Accounts Type Not Available"),
                    ("AUDIT EXEMPTION SUBSIDIARY", "Audit Exemption Subsidiary"),
                    ("AUDITED ABRIDGED", "Audited Abridged"),
                    ("DORMANT", "Dormant"),
                    ("FILING EXEMPTION SUBSIDIARY", "Filing Exemption Subsidiary"),
                    ("FULL", "Full"),
                    ("GROUP", "Group"),
                    ("MEDIUM", "Medium"),
                    ("MICRO ENTITY", "Micro Entity"),
                    ("SMALL", "Small"),
                    ("TOTAL EXEMPTION FULL", "Total Exemption Full"),
                    ("TOTAL EXEMPTION SMALL", "Total Exemption Small"),
                    ("UNAUDITED ABRIDGED", "Unaudited Abridged"),
                    ("NO ACCOUNTS FILED", "No Accounts Filed"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
