# Generated by Django 3.2.5 on 2022-01-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0018_alter_organisationlocation_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255, unique=True)),
                ("single", models.BooleanField()),
            ],
            options={
                "verbose_name": "Vocabulary",
                "verbose_name_plural": "Vocabularies",
            },
        ),
        migrations.CreateModel(
            name="VocabularyEntries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=500)),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("current", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ftc.vocabularyentries",
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ftc.vocabulary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vocabulary Entry",
                "verbose_name_plural": "Vocabulary Entries",
                "unique_together": {("vocabulary", "code")},
            },
        ),
    ]
