# Generated by Django 3.2.11 on 2022-02-01 13:24

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0024_alter_vocabulary_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="linked_orgs",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200),
                blank=True,
                null=True,
                size=None,
                verbose_name="Linked organisations",
            ),
        ),
    ]
