# Generated by Django 4.1.6 on 2023-02-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0027_organisation_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="latestEmployees",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Latest employees"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="latestSpending",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Latest expenditure"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="latestVolunteers",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Latest volunteers"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="trusteeCount",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Count of trustees"
            ),
        ),
    ]
