# Generated by Django 4.2.2 on 2023-07-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftc", "0028_organisation_latestemployees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationlocation",
            name="geo_lsoa21",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=9,
                null=True,
                verbose_name="Lower Super Output Area (2011)",
            ),
        ),
        migrations.AddField(
            model_name="organisationlocation",
            name="geo_msoa21",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=9,
                null=True,
                verbose_name="Middle Super Output Area (2021)",
            ),
        ),
        migrations.AddField(
            model_name="organisationlocation",
            name="geo_oa21",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Output Area (2021)"
            ),
        ),
        migrations.AlterField(
            model_name="organisationlocation",
            name="geo_lsoa11",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=9,
                null=True,
                verbose_name="Lower Super Output Area (2011)",
            ),
        ),
        migrations.AlterField(
            model_name="organisationlocation",
            name="geo_msoa11",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=9,
                null=True,
                verbose_name="Middle Super Output Area (2021)",
            ),
        ),
        migrations.AlterField(
            model_name="organisationlocation",
            name="geo_oa11",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Output Area (2011)"
            ),
        ),
    ]
