# Generated by Django 4.2.2 on 2023-08-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ftcprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseUser",
            fields=[
                (
                    "usename",
                    models.CharField(help_text="Name of this user", max_length=100),
                ),
                (
                    "usesysid",
                    models.IntegerField(
                        help_text="ID of this user", primary_key=True, serialize=False
                    ),
                ),
                (
                    "usecreatedb",
                    models.BooleanField(help_text="User can create databases"),
                ),
                ("usesuper", models.BooleanField(help_text="User is a superuser")),
                (
                    "userepl",
                    models.BooleanField(
                        help_text="User can initiate streaming replication and put the system in and out of backup mode."
                    ),
                ),
                (
                    "usebypassrls",
                    models.BooleanField(
                        help_text="User bypasses every row-level security policy"
                    ),
                ),
                (
                    "passwd",
                    models.CharField(
                        blank=True,
                        help_text="Not the password (always reads as ********)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "valuntil",
                    models.DateTimeField(
                        blank=True,
                        help_text="Password expiry time (only used for password authentication)",
                        null=True,
                    ),
                ),
                (
                    "useconfig",
                    models.TextField(
                        blank=True,
                        help_text="Session defaults for run-time configuration variables",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "pg_user",
                "ordering": ("usename",),
                "managed": False,
            },
        ),
    ]
