# Generated by Django 3.1.1 on 2020-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcd', models.CharField(max_length=7, unique=True)),
                ('pcd2', models.CharField(max_length=8, unique=True)),
                ('pcds', models.CharField(max_length=8, unique=True)),
                ('dointr', models.DateField()),
                ('doterm', models.DateField(blank=True, null=True)),
                ('usertype', models.IntegerField(choices=[(None, 'Unknown'), (0, 'Small users'), (1, 'Large users')])),
                ('oseast1m', models.IntegerField(blank=True, null=True)),
                ('osnrth1m', models.IntegerField(blank=True, null=True)),
                ('osgrdind', models.IntegerField(choices=[(1, 'within the building of the matched address closest to the postcode mean'), (2, 'as for status value 1, except by visual inspection of Landline maps (Scotland only)'), (3, 'approximate to within 50 metres;'), (4, 'postcode unit mean (mean of matched addresses with the same postcode, but not snapped to a building)'), (5, 'imputed by ONS, by reference to surrounding postcode grid references'), (6, 'postcode sector mean, (mainly PO Boxes)'), (8, 'postcode terminated prior to Gridlink® initiative, last known ONS postcode grid reference'), (9, 'no grid reference available')])),
                ('oa11', models.CharField(blank=True, max_length=9, null=True)),
                ('cty', models.CharField(blank=True, max_length=9, null=True)),
                ('ced', models.CharField(blank=True, max_length=9, null=True)),
                ('laua', models.CharField(blank=True, max_length=9, null=True)),
                ('ward', models.CharField(blank=True, max_length=9, null=True)),
                ('hlthau', models.CharField(blank=True, max_length=9, null=True)),
                ('nhser', models.CharField(blank=True, max_length=9, null=True)),
                ('ctry', models.CharField(blank=True, max_length=9, null=True)),
                ('rgn', models.CharField(blank=True, max_length=9, null=True)),
                ('pcon', models.CharField(blank=True, max_length=9, null=True)),
                ('eer', models.CharField(blank=True, max_length=9, null=True)),
                ('teclec', models.CharField(blank=True, max_length=9, null=True)),
                ('ttwa', models.CharField(blank=True, max_length=9, null=True)),
                ('pct', models.CharField(blank=True, max_length=9, null=True)),
                ('nuts', models.CharField(blank=True, max_length=9, null=True)),
                ('npark', models.CharField(blank=True, max_length=9, null=True)),
                ('lsoa11', models.CharField(blank=True, max_length=9, null=True)),
                ('msoa11', models.CharField(blank=True, max_length=9, null=True)),
                ('wz11', models.CharField(blank=True, max_length=9, null=True)),
                ('ccg', models.CharField(blank=True, max_length=9, null=True)),
                ('bua11', models.CharField(blank=True, max_length=9, null=True)),
                ('buasd11', models.CharField(blank=True, max_length=9, null=True)),
                ('ru11ind', models.CharField(blank=True, max_length=2, null=True)),
                ('oac11', models.CharField(blank=True, max_length=3, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('lep1', models.CharField(blank=True, max_length=9, null=True)),
                ('lep2', models.CharField(blank=True, max_length=9, null=True)),
                ('pfa', models.CharField(blank=True, max_length=9, null=True)),
                ('imd', models.IntegerField(blank=True, null=True)),
                ('calncv', models.CharField(blank=True, max_length=9, null=True)),
                ('stp', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
