# Generated by Django 3.1.1 on 2020-10-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20201001_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationLocation',
        ),
    ]
