# Generated by Django 3.1.1 on 2021-02-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0005_delete_organisationlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="geoLookup",
            fields=[
                (
                    "geoCode",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Geo Code",
                    ),
                ),
                (
                    "geoCodeType",
                    models.CharField(
                        db_index=True, max_length=25, verbose_name="Geo Code Type"
                    ),
                ),
                (
                    "geo_iso",
                    models.CharField(
                        db_index=True,
                        default="GB",
                        max_length=3,
                        verbose_name="ISO3166-1 Country Code",
                    ),
                ),
                (
                    "geo_oa11",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Output Area"
                    ),
                ),
                (
                    "geo_cty",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="County"
                    ),
                ),
                (
                    "geo_laua",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        null=True,
                        verbose_name="Local Authority",
                    ),
                ),
                (
                    "geo_ward",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Ward"
                    ),
                ),
                (
                    "geo_ctry",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "geo_rgn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        null=True,
                        verbose_name="Region",
                    ),
                ),
                (
                    "geo_pcon",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        null=True,
                        verbose_name="Parliamentary Constituency",
                    ),
                ),
                (
                    "geo_ttwa",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="Travel to Work Area",
                    ),
                ),
                (
                    "geo_lsoa11",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        null=True,
                        verbose_name="Lower Super Output Area",
                    ),
                ),
                (
                    "geo_msoa11",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        null=True,
                        verbose_name="Middle Super Output Area",
                    ),
                ),
                (
                    "geo_lep1",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="Local Enterprise Partnership 1",
                    ),
                ),
                (
                    "geo_lep2",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="Local Enterprise Partnership 2",
                    ),
                ),
                (
                    "geo_lat",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "geo_long",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
            ],
        ),
    ]
