# Generated by Django 3.0.6 on 2020-06-01 15:37

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aootype', models.CharField(max_length=1)),
                ('aookey', models.IntegerField()),
                ('aooname', models.CharField(db_index=True, max_length=200)),
                ('aoosort', models.CharField(db_index=True, max_length=200)),
                ('welsh', models.BooleanField(verbose_name='In Wales')),
                ('GSS', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='ONS Geocode for Local Authority')),
                ('ISO3166_1', models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='ISO3166-1 country code (2 character)')),
                ('ISO3166_1_3', models.CharField(blank=True, db_index=True, max_length=3, null=True, verbose_name='ISO3166-1 country code (3 character)')),
                ('ISO3166_2_GB', models.CharField(blank=True, db_index=True, max_length=6, null=True, verbose_name='ISO3166-2 region code (GB only)')),
                ('ContinentCode', models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='ISO3166-2 region code (GB only)')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.AreaOfOperation', verbose_name='Parent area')),
            ],
            options={
                'unique_together': {('aootype', 'aookey')},
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('constitution', models.TextField(blank=True, null=True)),
                ('geographical_spread', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(db_index=True)),
                ('date_registered', models.DateField(blank=True, db_index=True, null=True)),
                ('date_removed', models.DateField(blank=True, db_index=True, null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('company_number', models.CharField(blank=True, max_length=200, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('first_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('income', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('spending', models.BigIntegerField(blank=True, null=True)),
                ('latest_fye', models.DateField(blank=True, null=True)),
                ('dual_registered', models.BooleanField(blank=True, null=True)),
                ('areas_of_operation', models.ManyToManyField(to='charity.AreaOfOperation')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('single', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.VocabularyEntries')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='charity.Vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='CharityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('name_type', models.CharField(db_index=True, max_length=200)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='charity.Charity')),
            ],
        ),
        migrations.AddField(
            model_name='charity',
            name='classification',
            field=models.ManyToManyField(to='charity.VocabularyEntries'),
        ),
        migrations.CreateModel(
            name='CharityFinancial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fyend', models.DateField(db_index=True)),
                ('fystart', models.DateField(blank=True, null=True)),
                ('income', models.BigIntegerField(blank=True, null=True)),
                ('spending', models.BigIntegerField(blank=True, null=True)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='charity.Charity')),
            ],
            options={
                'unique_together': {('charity', 'fyend')},
            },
        ),
    ]
