# Generated by Django 3.0.6 on 2020-06-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_squashed_0009_auto_20200606_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityraw',
            name='spider',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
