# Generated by Django 3.0.6 on 2020-06-04 12:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0006_auto_20200601_2109'),
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('scrape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftc.Scrape')),
            ],
        ),
    ]
