# Generated by Django 3.0.6 on 2020-06-04 13:30

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_charityraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityraw',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
