# Generated by Django 3.0.6 on 2020-06-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20200604_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityname',
            name='normalisedName',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='charityname',
            unique_together={('charity', 'name')},
        ),
    ]
