# Generated by Django 3.0.6 on 2020-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_charityraw_spider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityfinancial',
            name='detail',
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='account_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('consolidated', 'Consolidated'), ('charity', 'Charity')], default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='asset_close',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='asset_gain',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='asset_open',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='cash_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='credit_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='credit_long',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='current_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='employees',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_charble',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_dep',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_gov',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_grant',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_invest',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_other',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_support',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_trade',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='exp_vol',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='fixed_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='funds_end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='funds_restrict',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='funds_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='funds_unrestrict',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='inc_char',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='inc_end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='inc_fr',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='inc_invest',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='inc_leg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='inc_other',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='inc_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='inc_vol',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='invest_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='invest_gain',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='open_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='pension_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='pension_gain',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='reserves',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='total_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityfinancial',
            name='volunteers',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
