# Generated by Django 3.0.6 on 2020-06-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20200604_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
