# Generated by Django 3.0.6 on 2020-06-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_auto_20200606_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabularyentries',
            unique_together={('vocabulary', 'code')},
        ),
    ]
