# Generated by Django 3.0.6 on 2020-06-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_auto_20200606_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyentries',
            name='code',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vocabularyentries',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
