# Generated by Django 3.0.6 on 2020-06-08 00:28

import dbview.helpers
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ftc', '0001_initial'), ('ftc', '0002_organisation_location'), ('ftc', '0003_organisationlink'), ('ftc', '0004_organisationlink_source'), ('ftc', '0005_auto_20200531_0042'), ('ftc', '0006_auto_20200601_2109'), ('ftc', '0007_linkedorganisation'), ('ftc', '0008_auto_20200606_1451'), ('ftc', '0009_auto_20200607_2230')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('slug', models.SlugField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider', models.CharField(max_length=200)),
                ('result', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(auto_now=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('items', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('running', 'In progress'), ('success', 'Finished successfully'), ('errors', 'Finished with errors'), ('failed', 'Failed to complete')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=200)),
                ('orgIDs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, db_index=True, null=True, size=None)),
                ('name', models.CharField(max_length=255)),
                ('alternateName', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, db_index=True, null=True, size=None)),
                ('charityNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('companyNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('streetAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLocality', models.CharField(blank=True, max_length=255, null=True)),
                ('addressRegion', models.CharField(blank=True, max_length=255, null=True)),
                ('addressCountry', models.CharField(blank=True, max_length=255, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('latestIncome', models.BigIntegerField(blank=True, null=True)),
                ('latestIncomeDate', models.DateField(blank=True, null=True)),
                ('dateRegistered', models.DateField(blank=True, null=True)),
                ('dateRemoved', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.CharField(blank=True, max_length=200, null=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('organisationType', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, db_index=True, null=True, size=None)),
                ('spider', models.CharField(db_index=True, max_length=200)),
                ('organisationTypePrimary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ftc.OrganisationType')),
                ('scrape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftc.Scrape')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftc.Source')),
            ],
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['orgIDs'], name='ftc_organis_orgIDs_6b135b_gin'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['alternateName'], name='ftc_organis_alterna_37835c_gin'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['organisationType'], name='ftc_organis_organis_8a0172_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='organisation',
            unique_together={('org_id', 'scrape')},
        ),
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganisationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id_a', models.CharField(db_index=True, max_length=255)),
                ('org_id_b', models.CharField(db_index=True, max_length=255)),
                ('spider', models.CharField(db_index=True, max_length=200)),
                ('scrape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftc.Scrape')),
                ('source', models.ForeignKey(default='rsl', on_delete=django.db.models.deletion.CASCADE, to='ftc.Source')),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.AlterField(
            model_name='organisation',
            name='alternateName',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisationType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        dbview.helpers.CreateView(
            name='LinkedOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id_a', models.CharField(max_length=255)),
                ('org_id_b', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='linked_orgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['linked_orgs'], name='ftc_organis_linked__006ef0_gin'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisationTypePrimary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='ftc.OrganisationType'),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
