# Generated by Django 3.0.6 on 2020-05-30 21:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
