# Generated by Django 3.0.6 on 2020-06-08 10:09

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ftc.models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0001_squashed_0009_auto_20200607_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgidScheme',
            fields=[
                ('code', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
