# Generated by Django 3.0.6 on 2020-05-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0002_organisation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id_a', models.CharField(db_index=True, max_length=255)),
                ('org_id_b', models.CharField(db_index=True, max_length=255)),
                ('spider', models.CharField(db_index=True, max_length=200)),
                ('scrape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftc.Scrape')),
            ],
            options={
                'unique_together': {('org_id_a', 'org_id_b', 'scrape')},
            },
        ),
    ]
