# Generated by Django 3.0.6 on 2020-06-09 16:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ftc.models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0003_auto_20200608_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
