# Generated by Django 3.0.6 on 2020-05-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0004_organisationlink_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationlink',
            unique_together=set(),
        ),
    ]
