# Generated by Django 3.0.6 on 2020-06-01 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0005_auto_20200531_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='alternateName',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisationType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
    ]
