# Generated by Django 3.0.6 on 2020-06-06 13:51

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0007_linkedorganisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='linked_orgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['linked_orgs'], name='ftc_organis_linked__006ef0_gin'),
        ),
    ]
