# Generated by Django 3.0.6 on 2020-06-07 21:30

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0008_auto_20200606_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisationTypePrimary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='ftc.OrganisationType'),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
